name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      buildDir: '${{ github.workspace }}/build/'

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
          export CC=gcc64
          export CXX=g++64

      - name: compile runtime
        run: |
          cd ~
          git clone https://github.com/awslabs/aws-lambda-cpp.git
          cd aws-lambda-cpp
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DBUILD_SHARED_LIBS=OFF \
                   -DCMAKE_INSTALL_PREFIX=~/out
          make && make install

      - name: cache aws sdk
        id: cache-aws
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/vcpkg/archives
          key: ${{ runner.os }}-aws-cache

      - name: install aws sdk
        run: vcpkg install "aws-sdk-cpp[core, lambda]" --recurse

      - name: build lambda
        run: |
          vcpkg integrate install
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=~/out \
            -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          make
          make aws-lambda-package-passwords

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: deploy lambda
        run: |
          cd build
          aws lambda update-function-code \
            --function-name passwords \
            --zip-file fileb://passwords.zip
